apiVersion: v1
kind: Service
metadata:
  name: my-web-service
spec:
  selector:
    app: nginx-web-app  
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 80  
      nodePort: 30001  
  type: NodePort
